config/routes.rb
SdriptDashboard::Application.routes.draw do
  resources :action_items

  root :to => 'dashboard#index'

end

app/models/action_item.rb
class ActionItem < ActiveRecord::Base
  
end

app/controllers/action_items_controller.rb
class ActionItemsController < ApplicationController
  def index
    @action_items = ActionItem.all
  end
  
  def new
    @action_item = ActionItem.new
  end
  
  def create
    action_item = ActionItem.new(params[:action_item])
    action_item.origination = Time.now.to_s(:db)
    action_item.save
    redirect_to action_items_path
  end
  
  def edit
    @action_item = ActionItem.find(params[:id])
  end
  
  def update
    action_item = ActionItem.find(params[:id])
    action_item.update_attributes(params[:action_item])
    redirect_to action_items_path
  end
  
  def show
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/helpers/action_items_helper.rb
module ActionItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/action_items/_form.html.erb
<div>
  Due: <%= f.text_field :due %>
</div>
<div>
  Assignee: <%= f.text_field :assignee %>
</div>
<div>
  Team Lead: <%= f.text_field :team_lead %>
</div>
<div>
  State: <%= f.select :state, ['Open', 'Team Lead Review', 'QA Review', 'Closed'] %>
</div>
<div>
  Configuration Item: <%= f.text_field :ci %>
</div>
<div>
  Priority: <%= f.text_field :priority %>
</div>
<div>
  Description: <%= f.text_area :description %>
</div>
<div>
  Closure Criteria: <%= f.text_area :closure_criteria %>
</div>

app/views/action_items/edit.html.erb
<%= form_for @action_item, :method => :put do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= f.submit %>
<% end %>

app/views/action_items/index.html.erb
<table border="0" cellspacing="5" cellpadding="5">
  <tr><th>Header</th></tr>

  <% @action_items.each do |action_item| %>
    <tr>
      <td>
        <%= action_item.priority %>
      </td>
      <td>
        <%= action_item.assignee %>
      </td>
      <td>
        <%= action_item.id %>
      </td>
      <td>
        <%= action_item.ci %>
      </td>
      <td>
        <%= action_item.description %>
      </td>
      <td>
        <%= action_item.closure_criteria %>
      </td>
      <td>
        <%= action_item.due %>
      </td>
      <td>
        <%= link_to "Edit Action Item", edit_action_item_path(action_item) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/action_items/new.html.erb
<%= form_for @action_item do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SdriptDashboard</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag 'screen.css', :media => 'screen, projection' %>
  <%= stylesheet_link_tag 'print.css', :media => 'print' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'ie.css', :media => 'screen, projection' %><![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>